### ISSUE TITLE
-0 is never matched

### ISSUE THREAD

**Issue by qzhang503** [s-u/fastmatch#12]
# different outputs
xs <- ceiling(log(c(114.0916, 114.9999)/115)/log(1+1E-6))
match(xs, xs); fastmatch::fmatch(xs, xs)

# the same outputs
ys <- as.integer(xs)
match(ys, ys); fastmatch::fmatch(ys, ys)

**Comment by s-u** [comment]
Thanks, the normalization of zero in doubles didn't quite work as designed since the normalized value (0) was compared to the original (-0) and thus -0 would never match - most simple example:

```
> fastmatch::fmatch(-0,-0)
[1] NA
```
now fixed
```
> fastmatch::fmatch(c(0,-0),-0)
[1] 1 1
```
