### ISSUE TITLE
Add %in% analogue

### ISSUE THREAD

**Issue by joshuaulrich** [s-u/fastmatch#2]
A [question on StackOverlow](http://stackoverflow.com/q/32934933/271616) asked about a faster version of `%in%` analogous to `fastmatch::fmatch` for `base::match`. Since `%in%` is basically a simple wrapper around `match`, it would be an easy addition... unless I'm overlooking something.

For example:

``` r
`%fin%` <- function(x, table) {
  fmatch(x, table, nomatch = 0L) > 0L
}
```

**Comment by s-u** [comment]
Great idea!

**Comment by joshuaulrich** [comment]
Would you like me to create a PR where I add `%fin%` to fastmatch.R and update fastmatch.Rd accordingly?
