### ISSUE TITLE
Release 1.1 or a 1.0 bugfix release, please?

### ISSUE THREAD

**Issue by namelessjon** [s-u/fastmatch#5]
Hi

I'm getting bitten by "bugfix: fix crash when a newly unserialized hash table is used (since the table hash is not stored during serialization)."

Would it be possible to release a version of fastmatch that doesn't suffer from this problem please?

**Comment by s-u** [comment]
I'll clean up 1.1 (it is missing some docs) and push it to CRAN.

**Comment by namelessjon** [comment]
Thank you, really appreciate that :smile:

**Comment by s-u** [comment]
Now on CRAN

**Comment by namelessjon** [comment]
Just updated.  Thank you for the library and this release
