### ISSUE TITLE
NA match

### ISSUE THREAD

**Issue by juanpide** [s-u/fastmatch#6]
Hello.

The reason I use base's %in%  or match commands is because it makes easy to match values no matter they are numbers, characters or even NAs.

```
match(c(1,0,NA),NA)   NA, NA, 1
c(1,0,NA) %in% NA  gives  FALSE, FALSE, TRUE
```
I specially like the latter one.

But
`fmatch(c(1,0,NA),NA)  gives NA, NA, NA   (useless)`

If fastmatch is supposed to improve base::_match_ I think it should mimic it's behaviour with NA.

**Comment by s-u** [comment]
Sorry, but I get

    > library(fastmatch)
    > fmatch(c(1,0,NA),NA)
    [1] NA NA  1

Can you, please, supply details on versions (R + fastmatch + OS) and platform?

**Comment by joshuaulrich** [comment]
The latest version of `fmatch` in the repository already does what you want.  You're probably using the CRAN version.

```r
R> match(c(1, 0, NA_real_), NA_real_)
[1] NA NA  1
R> fastmatch::fmatch(c(1, 0, NA_real_), NA_real_)
[1] NA NA  1
R> packageVersion("fastmatch")
[1] '1.1.0'
```

Using the version on CRAN:

```r
R> match(c(1, 0, NA_real_), NA_real_)
[1] NA NA  1
R> fastmatch::fmatch(c(1, 0, NA_real_), NA_real_)
[1] NA NA NA
R> packageVersion("fastmatch")
[1] '1.0.4'
```

**Comment by s-u** [comment]
I guess it's time to push it to CRAN ;)

**Comment by juanpide** [comment]
OK, now it works, thanks.
